In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('Precily_Text_Similarity.csv')
#df['similarity'] = np.nan
df

,text1,text2
0,broadband challenges tv viewing the number of ...,gardener wins double in glasgow britain s jaso...
1,rap boss arrested over drug find rap mogul mar...,amnesty chief laments war failure the lack of ...
2,player burn-out worries robinson england coach...,hanks greeted at wintry premiere hollywood sta...
3,hearts of oak 3-2 cotonsport hearts of oak set...,redford s vision of sundance despite sporting ...
4,sir paul rocks super bowl crowds sir paul mcca...,mauresmo opens with victory in la amelie maure...
...,...,...
2995,uk directors guild nominees named martin scors...,steel firm to cut 45 000 jobs mittal steel ...
2996,u2 to play at grammy awards show irish rock ba...,israel looks to us for bank chief israel has a...
2997,pountney handed ban and fine northampton coach...,india and iran in gas export deal india has si...
2998,belle named best scottish band belle & sebas...,mido makes third apology ahmed mido hossam h...
2999,criminal probe on citigroup deals traders at u...,former ni minister scott dies former northern ...

In [4]:
pip install spacy

Collecting spacy
  Downloading spacy-3.6.0-cp39-cp39-win_amd64.whl (12.3 MB)
     --------------------------------------- 12.3/12.3 MB 44.5 kB/s eta 0:00:00
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (1.10.7)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (5.2.1)
Requirement already satisfied: numpy>=1.15.0 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (1.21.5)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.8-cp39-cp39-win_amd64.whl (96 kB)
     --------------------------------------- 96.8/96.8 kB 41.6 kB/s eta 0:00:00
Collecting thinc<8.2.0,>=8.1.8
  Downloading thinc-8.1.10-cp39-cp39-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 23.0 kB/s eta 0:00:00
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.9-cp39-cp39-win_amd64.whl (18 kB)
Collecting pathy>=0.10.0
  Downloading pathy-0.10.2-py3-none-any.whl (48 kB)
     --------------------------------------- 48.9/48.9 kB 31.7 kB/s eta 0:00:00
Collecting srsly<3.0.0,>=2.4.3
  Downloading srsly-2.4.6-cp39-cp39-win_amd64.whl (482 kB)
     ------------------------------------- 482.8/482.8 kB 38.5 kB/s eta 0:00:00
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (2.28.1)
Collecting typer<0.10.0,>=0.3.0
  Downloading typer-0.9.0-py3-none-any.whl (45 kB)
     --------------------------------------- 45.9/45.9 kB 53.0 kB/s eta 0:00:00
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (4.64.1)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.7-cp39-cp39-win_amd64.whl (30 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0
  Downloading spacy_loggers-1.0.4-py3-none-any.whl (11 kB)
Collecting wasabi<1.2.0,>=0.9.1
  Downloading wasabi-1.1.2-py3-none-any.whl (27 kB)
Requirement already satisfied: jinja2 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (2.11.3)
Requirement already satisfied: setuptools in c:\users\prath\anaconda3\lib\site-packages (from spacy) (63.4.1)
Collecting langcodes<4.0.0,>=3.2.0
  Downloading langcodes-3.3.0-py3-none-any.whl (181 kB)
     ------------------------------------- 181.6/181.6 kB 34.0 kB/s eta 0:00:00
Collecting catalogue<2.1.0,>=2.0.6
  Downloading catalogue-2.0.8-py3-none-any.whl (17 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\prath\anaconda3\lib\site-packages (from spacy) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\prath\anaconda3\lib\site-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\prath\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\prath\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prath\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\prath\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\prath\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Collecting blis<0.8.0,>=0.7.8
  Downloading blis-0.7.9-cp39-cp39-win_amd64.whl (7.0 MB)
     -                                        0.3/7.0 MB 19.4 kB/s eta 0:05:45
Note: you may need to restart the kernel to use updated packages.

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "c:\Users\prath\anaconda3\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "c:\Users\prath\anaconda3\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "c:\Users\prath\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "c:\Users\prath\anaconda3\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "c:\Users\prath\anaconda3\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\Users\prath\anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\Users\prath\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

In [3]:
!python -m spacy download en_core_web_md

c:\Users\prath\anaconda3\python.exe: No module named spacy

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

nlp = spacy.load('en_core_web_md')
def compute_similarity(text1, text2):
    doc1 = nlp(text1)
    doc2 = nlp(text2)
    similarity_score = doc1.similarity(doc2)
    return similarity_score
count_vect = CountVectorizer()
vectorizer = TfidfVectorizer()
output1=[]
output2=[]
output3 = []
for index, row in df.iterrows():
  doc1 = nlp(row['text1'])
  doc1 = " ".join([token.text for token in doc1 if not token.is_stop and not token.is_punct])
  doc_1 = nlp(doc1)
  doc2 = nlp(row['text2'])
  doc2 = " ".join([token.text for token in doc2 if not token.is_stop and not token.is_punct])
  doc_2 = nlp(doc2)
  similarity_score = doc_1.similarity(doc_2)
  corpus = [row['text1'],row['text2']]
  trsfm=vectorizer.fit_transform(corpus)
  count = count_vect.fit_transform(corpus)
  output1.append(cosine_similarity(trsfm[0:1], trsfm)[0][1])
  output2.append(cosine_similarity(count[0:1], count)[0][1])
  output3.append(similarity_score)

In [ ]:
df['tf_similarity score'] = np.array(output1)
df['count_vector_similarity score'] = np.array(output2)
df['spacy_similarity'] = np.array(output3)
df

,text1,text2,tf_similarity score,count_vector_similarity score,spacy_similarity
0,broadband challenges tv viewing the number of ...,gardener wins double in glasgow britain s jaso...,0.551968,0.685256,0.681847
1,rap boss arrested over drug find rap mogul mar...,amnesty chief laments war failure the lack of ...,0.312518,0.431582,0.741980
2,player burn-out worries robinson england coach...,hanks greeted at wintry premiere hollywood sta...,0.408212,0.564167,0.798685
3,hearts of oak 3-2 cotonsport hearts of oak set...,redford s vision of sundance despite sporting ...,0.530670,0.665098,0.584314
4,sir paul rocks super bowl crowds sir paul mcca...,mauresmo opens with victory in la amelie maure...,0.424369,0.556794,0.756248
...,...,...,...,...,...
2995,uk directors guild nominees named martin scors...,steel firm to cut 45 000 jobs mittal steel ...,0.233185,0.360799,0.662692
2996,u2 to play at grammy awards show irish rock ba...,israel looks to us for bank chief israel has a...,0.361240,0.504299,0.624168
2997,pountney handed ban and fine northampton coach...,india and iran in gas export deal india has si...,0.280158,0.416412,0.706340
2998,belle named best scottish band belle & sebas...,mido makes third apology ahmed mido hossam h...,0.460974,0.605117,0.812392
2999,criminal probe on citigroup deals traders at u...,former ni minister scott dies former northern ...,0.442060,0.592286,0.863432

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk
from wordcloud import WordCloud
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize.treebank import TreebankWordDetokenizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import Pipeline
import spacy
from collections import Counter
nlp = spacy.load('en_core_web_sm')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
copydata=df.copy()
data=df

In [ ]:
def remove_punc(copydata):
  pattern = r'[' + string.punctuation + ']'
  copydata['text1']=data['text1'].map(lambda m:re.sub(pattern," ",m))
  copydata['text2']=data['text2'].map(lambda m:re.sub(pattern," ",m))
  return copydata


def lower(copydata):
  copydata['text1']=copydata['text1'].map(lambda m:m.lower())
  copydata['text2']=copydata['text2'].map(lambda m:m.lower())
  return copydata


def tokenization(text):
    tokens = re.split(' ',text)
    return tokens

def token(copydata):
  copydata['text1']= copydata['text1'].apply(lambda x: tokenization(x))
  copydata['text2']= copydata['text2'].apply(lambda x: tokenization(x))
  return copydata


sw=nltk.corpus.stopwords.words('english')

def remove_SW(copydata):
   copydata['text1']=copydata['text1'].apply(lambda x: [item for item in x if item not in sw])
   copydata['text2']=copydata['text2'].apply(lambda x: [item for item in x if item not in sw])
   return copydata


def remove_digits(copydata):
  copydata['text1']=copydata['text1'].apply(lambda x: [item for item in x if not item.isdigit()])
  copydata['text2']=copydata['text2'].apply(lambda x: [item for item in x if not item.isdigit()])
  return copydata


lemmatizer = WordNetLemmatizer()

def lemmatize(copydata):
  copydata['text1']=copydata['text1'].apply(lambda x: [lemmatizer.lemmatize(item) for item in x])
  copydata['text2']=copydata['text2'].apply(lambda x: [lemmatizer.lemmatize(item) for item in x])
  return copydata


def remove_empty_tokens(copydata):
  copydata['text1']=copydata['text1'].apply(lambda x: [item for item in x if item !=''])
  copydata['text2']=copydata['text2'].apply(lambda x: [item for item in x if item !=''])
  return copydata


def remove_single_letters(copydata):
  copydata['text1']=copydata['text1'].apply(lambda x: [item for item in x if len(item) > 1])
  copydata['text2']=copydata['text2'].apply(lambda x: [item for item in x if len(item) > 1])
  return copydata


def detoken(copydata):
  copydata['text1']= copydata['text1'].apply(lambda x: TreebankWordDetokenizer().detokenize(x))
  copydata['text2']= copydata['text2'].apply(lambda x: TreebankWordDetokenizer().detokenize(x))
  return copydata

def replace_spaces(x,space,second):
  result = x.replace(space, second)
  return result
def remove_space(copydata):
  copydata['text1']= copydata['text1'].apply(lambda x: replace_spaces(x,'  ',' '))
  copydata['text2']= copydata['text2'].apply(lambda x: replace_spaces(x,'  ',' '))
  return copydata
def count_vcr():
  similarity=[]
  for i in range(len(copydata)):
    doc1=copydata['text1'][i]
    doc2=copydata['text2'][i]
    docs=(doc1,doc2)
    matrix = CountVectorizer().fit_transform(docs)
    cosine_sim = cosine_similarity(matrix[0], matrix[1])[0][0]
    similarity.append(cosine_sim)
  return similarity


tfidf_vectorizer = TfidfVectorizer()
def similarity_fn():
  similarity=[]
  for i in range(len(copydata)):
    doc1=copydata['text1'][i]
    doc2=copydata['text2'][i]
    docs=(doc1,doc2)
    tfidf_matrix = tfidf_vectorizer.fit_transform(docs)
    cosine_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])[0][0]
    similarity.append(cosine_sim)
  return similarity

In [ ]:
bow_converter = CountVectorizer()
copydata.pipe(lower).pipe(token).pipe(remove_SW).pipe(remove_digits).pipe(remove_single_letters).pipe(lemmatize).pipe(remove_single_letters).pipe(detoken)
similarity=[]
similarity=count_vcr()
data_cvr=copydata.copy()
data_cvr['Similarity']=similarity
data_cvr[:5]

,text1,text2,tf_similarity score,count_vector_similarity score,Similarity
0,broadband challenge tv viewing number european...,gardener win double glasgow britain jason gard...,0.551968,0.685256,0.107132
1,rap bos arrested drug find rap mogul marion su...,amnesty chief lament war failure lack public o...,0.312518,0.431582,0.036569
2,player burn-out worry robinson england coach a...,hank greeted wintry premiere hollywood star to...,0.408212,0.564167,0.067508
3,heart oak 3-2 cotonsport heart oak set ghanaia...,redford vision sundance despite sporting cordu...,0.530670,0.665098,0.040419
4,sir paul rock super bowl crowd sir paul mccart...,mauresmo open victory la amelie mauresmo maria...,0.424369,0.556794,0.097727

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
similarity=[]
similarity=similarity_fn()
data_tf=copydata.copy()
data_tf['Similarity']=similarity

In [ ]:
all_data=data_cvr.copy()
all_data['Count-Vec Similarity']=all_data['Similarity']
all_data=all_data.drop('Similarity',axis=1)
all_data['Tf-idf Similarity']=data_tf['Similarity']
all_data

,text1,text2,tf_similarity score,count_vector_similarity score,Count-Vec Similarity,Tf-idf Similarity
0,broadband challenge tv viewing number european...,gardener win double glasgow britain jason gard...,0.551968,0.685256,0.107132,0.061217
1,rap bos arrested drug find rap mogul marion su...,amnesty chief lament war failure lack public o...,0.312518,0.431582,0.036569,0.019313
2,player burn-out worry robinson england coach a...,hank greeted wintry premiere hollywood star to...,0.408212,0.564167,0.067508,0.036084
3,heart oak 3-2 cotonsport heart oak set ghanaia...,redford vision sundance despite sporting cordu...,0.530670,0.665098,0.040419,0.020959
4,sir paul rock super bowl crowd sir paul mccart...,mauresmo open victory la amelie mauresmo maria...,0.424369,0.556794,0.097727,0.054184
...,...,...,...,...,...,...
2995,uk director guild nominee named martin scorses...,steel firm cut job mittal steel one world larg...,0.233185,0.360799,0.015484,0.007904
2996,u2 play grammy award show irish rock band u2 p...,israel look bank chief israel asked banker for...,0.361240,0.504299,0.046982,0.024394
2997,pountney handed ban fine northampton coach bud...,india iran gas export deal india signed $40bn ...,0.280158,0.416412,0.013563,0.006938
2998,belle named best scottish band belle sebastian...,mido make third apology ahmed mido hossam made...,0.460974,0.605117,0.071049,0.037448
2999,criminal probe citigroup deal trader banking g...,former ni minister scott dy former northern ir...,0.442060,0.592286,0.063601,0.033805

In [ ]:
from flask import Flask, request, jsonify
import tensorflow as tf
import numpy as np

# Load the trained model
model = tf.keras.models.load_model("semantic_similarity_model.h5")  # Replace with the path to your trained model

# Create the Flask application
app = Flask(__name__)

# Define the API endpoint
@app.route('/predict', methods=['POST'])
def predict():
    # Extract the input data from the request body
    data = request.json
    text1 = data['text1']
    text2 = data['text2']

    # Preprocess the input data (tokenization, vectorization, etc.) - Modify as per your requirements

    # Make predictions using the pre-trained model
    prediction = model.predict([[text1, text2]])
    similarity_score = prediction[0][0]

    # Create the response body
    response = {
        'similarity score': float(similarity_score)
    }

    # Return the response as JSON
    return jsonify(response)

# Run the Flask application
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

In [ ]:
import spacy

In [ ]:
def compute_similarity(text1, text2):
    doc1 = nlp(text1)
    doc2 = nlp(text2)
    similarity_score = doc1.similarity(doc2)
    return similarity_score

In [ ]:
import spacy
from flask import Flask, request, jsonify

app = Flask(__name__)

# Load the pre-trained spaCy model
nlp = spacy.load('en_core_web_md')

# Function to compute the similarity score between two texts
def compute_similarity(text1, text2):
    doc1 = nlp(text1)
    doc2 = nlp(text2)
    similarity_score = doc1.similarity(doc2)
    return similarity_score

# API endpoint for semantic similarity
@app.route('/semantic-similarity', methods=['POST'])
def semantic_similarity():
    data = request.get_json()
    text1 = data['text1']
    text2 = data['text2']
    similarity_score = compute_similarity(text1, text2)
    response = {'similarity score': similarity_score}
    return jsonify(response)

if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit